#!/bin/bash
# Plugin for Nagios
# Written by M. Koettenstorfer (mko@lihas.de)
# Some additions by J. Schoepfer (jsc@lihas.de)
# Last Modified: 2008-11-06
#
# Description:
#
# This plugin will check howmany space in volume groups is free

# Don't change anything below here

# Nagios return codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4
LANG=C

# realsize=`ls -alh $1  | awk '{ print $5}'`
# realsize_with_file=`ls -alh $file | awk '{ print $5,$9}'`
PROGNAME=$(basename $0)

print_usage() {
	echo "Usage: $PROGNAME  -w <min size warning level in gb> -c <min size critical level in gb> -v volumegroupname"
	echo ""
}

print_help() {
	print_usage
	echo ""
	echo "This plugin will check howmany space in volume groups is free"
	echo ""
	exit 0
}

exitstatus=$STATE_UNKNOWN #default

while getopts ":w:c:v:h:" opt ;do
	case $opt in
		h)
			print_help
			exit $exitstatus
			;;
		w)
			warnlevel=$OPTARG
			;;
		c)
			critlevel=$OPTARG
			;;
		v)
			volumegroup=$OPTARG
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			;;
	esac
done

#Does volume group actually exist?
VGValid=$(vgdisplay 2>/dev/null | grep "$volumegroup" | wc -l )

if [[  -z "$volumegroup" ||  $VGValid = 0 ]]
then
	echo "Volumegroup $volumegroup wasn't valid or wasn't specified"
	echo "with \"-v Volumegroup\", bye."
	exit $STATE_UNKNOWN
fi


#Check the actual sizes
freespace=$(/sbin/vgdisplay "$volumegroup" | head -n19 | grep Free | cut -d'/' -f3 | cut -d' ' -f2 )
postfix=$(/sbin/vgdisplay "$volumegroup" | grep Free | cut -d'/' -f3 | cut -d' ' -f3 )
if [ $postfix == TB ]
then 
#	a=$( echo $freespace | tr ',' '.' )	
	freespace=$(echo "$freespace * 1000" | bc | cut -d'.' -f1 )

else
	freespace=$(echo $freespace| cut -d'.' -f1)
fi

# Check arguments for validity
if [[ -c $critlevel || -w $warnlevel ]] # Did we get warn and crit values?
then    
        echo "You must specify a warning and critical level"
	print_usage
        exitstatus=$STATE_UNKNOWN
        exit $exitstatus 
elif [ $warnlevel -le $critlevel ] # Do the warn/crit values make sense?
then
	echo "CRITICAL value of $critlevel GB is less than WARNING level of $warnlevel GB"
	print_usage
	exitstatus=$STATE_UNKNOWN
	exit $exitstatus
fi


# auswerten der abfrage

if [ "$freespace" -le "$critlevel" ]
then
	MESSAGE="VG $volumegroup CRITICAL verfuegbarer Platz ist $freespace GB gross"
	exitstatus=$STATE_CRITICAL
elif [ "$freespace" -le "$warnlevel" ]
then
	MESSAGE="VG $volumegroup WARNING verfuegbarer Platz ist $freespace GB gross"
	exitstatus=$STATE_WARNING
else
	MESSAGE="VG $volumegroup OK verfuegbarer Platz ist $freespace GB gross"
	exitstatus=$STATE_OK
fi 

echo $MESSAGE
exit $exitstatus
