#!/bin/bash
#check_vg_size
set -x 
# Plugin for Nagios
# Written by M. Koettenstorfer (mko@lihas.de)
# Some additions by J. Schoepfer (jsc@lihas.de)
# Last Modified: 2008-11-06
#
# Description:
#
# This plugin will check howmany space in volume groups is free

# Don't change anything below here

# Nagios return codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

SERVICEOUTPUT=""
SERVICEPERFDATA=""
LONGSERVICEOUTPUT=""

# realsize=`ls -alh $1  | awk '{ print $5}'`
# realsize_with_file=`ls -alh $file | awk '{ print $5,$9}'`
PROGNAME=$(basename $0)

exitstatus=$STATE_UNKNOWN #default
declare -a volumeGroups;
novg=0; #number of volume groups
allVG=false; #Will we use all volume groups we can find on system?

########################################################################
### DEFINE FUNCTIONS
########################################################################

print_usage() {
	echo "Usage: $PROGNAME  -w <min size warning level in gb> -c <min size critical level in gb> -v <volumegroupname> [-a]"
	echo "In case of usage of -a all volumegroups defined by -v will be ommited and all groups which are found on system are checked"
	echo ""
}

print_help() {
	print_usage
	echo ""
	echo "This plugin will check how many space in volume groups is free"
	echo "usage: "
	exit $STATE_UNKNOWN
}

	
checkArgValidity () {
# Check arguments for validity
	if [[ -z $critlevel || -z $warnlevel ]] # Did we get warn and crit values?
	then    
	        echo "You must specify a warning and critical level"
		print_usage
	        exitstatus=$STATE_UNKNOWN
	        exit $exitstatus 
	elif [ $warnlevel -le $critlevel ] # Do the warn/crit values make sense?
	then
		echo "CRITICAL value of $critlevel GB is less than WARNING level of $warnlevel GB"
		print_usage
		exitstatus=$STATE_UNKNOWN
		exit $exitstatus
	fi
}

#Does volume group actually exist?
volumeGroupExists () {
	local volGroup=$1
	VGValid=$(vgdisplay 2>/dev/null | grep "$volGroup" | wc -l )
	
	if [[  -z "$volGroup" ||  $VGValid = 0 ]]
	then
		echo "Volumegroup $volGroup wasn't valid or wasn't specified"
		echo "with \"-v Volumegroup\", bye."
		return 0
	else
		#The volume group exists
		return 1 
	fi
}

getNumberOfVGOnSystem () {
	local novg=$(vgs 2>/dev/null | wc -l)
	let novg--
	echo $novg
}

getAllVGOnSystem () {
	novg=$(getNumberOfVGOnSystem)
	for (( i=0; i < novg; i++)); do
		volumeGroups[$i]=$(vgs | tail -n $novg | awk '{print $1}')
	done
}

getColumnNoByName () {
        columnName=$1
        result=$(vgs 2>/dev/null | head -n1 | awk -v name=$columnName '
                BEGIN{}
                        { for(i=1;i<=NF;i++){
                              if ($i ~ name)
                                  {print i } }
                        }')

        echo $result
}

getSizesOfVolume () {
	volumeName="$1"
	#Check the actual sizes
	cn=$(getColumnNoByName "VFree")
	freespace=$(vgs 2>/dev/null | grep $volumeName | awk -v n=$cn '{print $n}' | sed -e 's/.$//')
	postfix=$(vgs 2>/dev/null | grep $volumeName | awk -v n=$cn '{print $n}'| sed -e 's/^.*\(.\)$/\1/')
	if [[ $postfix == T ]]
	then 
		freespace=$(echo "$freespace * 1000" | bc | cut -d'.' -f1 )
	
	else
		freespace=$(echo $freespace| cut -d'.' -f1)
	fi
}

setExitStatus () {
	local volGroup=$1
	local formerStatus=$1
	if [ "$freespace" -le "$critlevel" ]
	then
		SERVICEOUTPUT=$SERVICEOUTPUT"VG $volGroup CRITICAL Available space is $freespace GB"
		exitstatus=$STATE_CRITICAL
	elif [ "$freespace" -le "$warnlevel" ]
	then
		SERVICEOUTPUT=$SERVICEOUTPUT"VG $volGroup WARNING Available space is $freespace GB"
		exitstatus=$STATE_WARNING
	else
		SERVICEPERFDATA=$SERVICEOUTPUT"VG $volGroup OK Available space is $freespace GB"
		exitstatus=$STATE_OK
	fi 

	if [ $formerStatus -gt $exitstatus ]
	then
		exitstatus=$formerStatus
	fi
}


checkVolumeGroups () {
checkArgValidity
	for (( i=0; i < novg; i++ )); do
		local status=$STATE_UNKNOWN
		local currentVG=${volumeGroups[$i]}
	
		volumeGroupExists $currentVG  
		status=$?
		
		if (( $status )); then
			getSizesOfVolume "$currentVG" 
		else
			status=$STATE_UNKNOWN
		fi
		
		setExitStatus $status
	done
}

########################################################################
### RUN PROGRAM
########################################################################


########################################################################
#Read input values
while getopts ":w:c:v:h:a" opt ;do
	case $opt in
		h)
			print_help;
			exit $exitstatus;
			;;
		w)
			warnlevel=$OPTARG;
			;;
		c)
			critlevel=$OPTARG;
			;;
		v)
			if ( ! $allVG ); then
				volumeGroups[$novg]=$OPTARG;
				let novg++;
			fi
			;;
		a)
			allVG=true;
			getAllVGOnSystem;
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			;;
	esac
done

checkVolumeGroups


echo $SERVICEOUTPUT"|"$SERVICEPERFDATA"|"$LONGSERVICEOUTPUT
exit $exitstatus

